# Site settings
title: Fazal | Simple github pages blog
description: "Blog template, build with Jekyll."
url: "https://saim4u.github.io/SolutionBoxiz/"
author:
  name: "Fazal Kareem"
  email: "saim4u484@gmail.com"
  url: "https://saim4u.github.io/SolutionBoxiz/"

# Build settings
baseurl: /SolutionBoxiz/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
